### ISSUE TITLE
你装的是Ventura的吗

### ISSUE THREAD

**Issue by xd17** [millsguo/MSI-PRO-Z790-A-MAX-WIFI-D5-14700KF-RX6650XT-EFI#2]
首先感谢你提供efi文件，我装好ventura后，屏幕无法调节亮度和声音无法调节大小，你碰到了类似的情况吗

**Comment by millsguo** [comment]
是的，13.6.4，最新版本，不过我是PC，双屏，声音通过蓝牙音箱，都工作正常

你是安装在笔记本上吗？如果是笔记本，需要找相应的驱动
