### ISSUE TITLE
请问下MacOS的版本是多少

### ISSUE THREAD

**Issue by LLPPRR** [millsguo/MSI-PRO-Z790-A-MAX-WIFI-D5-14700KF-RX6650XT-EFI#3]
请问下MacOS的版本是多少，我安装 14.5 和 14.4.1 都在安装的时候黑屏

**Comment by millsguo** [comment]
我停留在13.6，因为14把蓝牙驱动删除了，目前13.6使用非常完美，暂时没有升级14的动力。
