### ISSUE TITLE
版本升级问题

### ISSUE THREAD

**Issue by wuheelph** [millsguo/MSI-PRO-Z790-A-MAX-WIFI-D5-14700KF-RX6650XT-EFI#5]
你好，你的同款主板，感谢分享，测试了一下，遇到如下问题：
1.  使用13.6.3镜像成功安装，正常运行，但自动更新13.6.7时，更新重启后卡进度条中间位置，后续也无法正常引导
2. 使用14.5镜像，可以启动安装，但安装过程进展到一定程度后不断重启

另外，两个建议：
1. 建议EFI中showpicker默认先打开，否则目前在安装的时候，由于scanpolicy扫描不到U盘的安装包入口，因此只有一个windows入口，U盘启动后，opencore无界面尝试引导windows，会让人误以为没有从U盘的opencore引导
2. 初始版本scanpolicy建议设置为0，原因同上

**Comment by millsguo** [comment]
1、更新后重启卡住，应该是没有选择新的安装引导项
2、14.5没有安装，无法提供帮助

建议收到，分享的是我目前正常使用的配置，这样启动速度最快。如果需要引导，自行打开即可。
